using UnityEngine;
using System.Collections;
using UnityEngine.SceneManagement;
using Assets.Scripts.Utils;

public class Menu : MonoBehaviour {

	// Use this for initialization
	void Start () {
		Screen.autorotateToLandscapeRight = true;
		Screen.autorotateToLandscapeLeft = true;
		Screen.autorotateToPortrait = false;
		Screen.autorotateToPortraitUpsideDown = false;
		Screen.orientation = ScreenOrientation.AutoRotation;
	}
	
	// Update is called once per frame
	void Update () {
		BackButtonHelper.quitOnBack();	
	}

	public void OnButtonPlayClicked()
	{
		SceneManager.LoadScene("Main");
	}

	public void OnButtonScoreClicked()
	{
		SceneManager.LoadScene("Scores");
	}

    public void OnButtonScoresClicked()
    {
        SceneManager.LoadScene("Scores");
    }

	public void OnButtonInfoClicked()
	{
		Application.OpenURL("http://2016.igem.org/Team:Ionis_Paris");
	}

}